import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Router from "next/router";
import Link from "next/link";
import { useKeycloak } from "@react-keycloak/ssr";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { initialized, keycloak } = useKeycloak();
  const { authenticated, idToken, logout = () => {} } = keycloak || {};

  const [user, setUser] = useState(null);

  useEffect(() => {
    if (!authenticated) {
      Router.replace("/login");
    }
    if (idToken) {
      const _user = JSON.parse(atob(idToken?.split(".")[1]));
      setUser(_user);
    }
  }, [initialized, authenticated, idToken]);

  return !initialized ? (
    <p>Carregando...</p>
  ) : (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!authenticated ? (
        <main className={styles.main}>
          <h1 className={styles.title}>Welcome to Next.js!</h1>
          <p className={styles.description}>Please do Login to continue</p>
          <Link href="/login">
            <p>Login</p>
          </Link>
        </main>
      ) : (
        <main className={styles.main}>
          <h1 className={styles.title}>Welcome</h1>
          <p className={styles.description}>{user?.name}</p>
          <Link href="/users">
            <a>View Users</a>
          </Link>
          <br></br>
          <button onClick={logout}>Logout</button>
        </main>
      )}
      <footer className={styles.footer}>
        Powered by{" "}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div>
  );
}
